// protoc-gen-swift-codable emits plain Swift `Codable` structs and `String`-backed
// enums from the contracts, so the Swift on-device provider speaks the fleet's
// protojson wire format with NO SwiftProtobuf runtime dependency. The contract stays
// the single source of truth, the Swift moves with it under `buf generate`, and the
// gen-drift gate catches any skew -- the same discipline as every other gen tree,
// just a lighter target than a full protobuf runtime.
//
// Scope (deliberately narrow): it generates only the packages the Swift side consumes
// today -- model.v1 and sidecar.v1 -- and only the field shapes those use: string,
// enum, nested message, repeated, and map<string,string>. It errors loudly on any
// other kind rather than emit something subtly wrong; teach it the new shape when a
// real need arrives. (buf runs every plugin over the whole module, so the package
// filter, like protoc-gen-fsm's enum filter, is how it stays scoped.)
//
// protojson conventions baked in:
//   - JSON keys are lowerCamelCase of the proto field name -- matched by the Swift
//     property names and CodingKeys, so default encoding is already protojson.
//   - enums are their value NAME as a string (the protojson default form).
//   - proto3 omits default-valued fields, so a field may be absent on decode; decoding
//     is therefore custom (absent -> the proto3 default), while encoding is synthesized.
package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// swiftPackages are the contract packages the Swift provider consumes. Every other
// package in the module is skipped.
var swiftPackages = map[string]bool{
	"model.v1":   true,
	"sidecar.v1": true,
}

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(1) // FEATURE_PROTO3_OPTIONAL
		for _, f := range gen.Files {
			if !f.Generate || !swiftPackages[string(f.Desc.Package())] {
				continue
			}
			if err := genSwift(gen, f); err != nil {
				return err
			}
		}
		return nil
	})
}

func genSwift(gen *protogen.Plugin, f *protogen.File) error {
	g := gen.NewGeneratedFile(f.GeneratedFilenamePrefix+".swift", f.GoImportPath)
	g.P("// Code generated by protoc-gen-swift-codable. DO NOT EDIT.")
	g.P("// source: ", f.Desc.Path())
	g.P()
	for _, e := range f.Enums {
		genEnum(g, e)
	}
	for _, m := range f.Messages {
		if err := genMessage(g, m); err != nil {
			return err
		}
	}
	return nil
}

func genEnum(g *protogen.GeneratedFile, e *protogen.Enum) {
	name := e.GoIdent.GoName
	g.P("public enum ", name, ": String, Codable, Sendable {")
	zero := ""
	for _, v := range e.Values {
		vn := string(v.Desc.Name())
		g.P("    case ", lowerCamel(vn), " = \"", vn, "\"")
		if v.Desc.Number() == 0 {
			zero = lowerCamel(vn)
		}
	}
	if zero == "" {
		zero = lowerCamel(string(e.Values[0].Desc.Name()))
	}
	g.P()
	g.P("    // The proto3 default (value 0); used when the field is absent on the wire.")
	g.P("    public static let `default` = ", name, ".", zero)
	g.P("}")
	g.P()
}

// swiftField is one resolved struct field: its Swift property name, Swift type, whether
// it is optional (a singular message has no proto3 default, so it is optional), and the
// default expression used in the memberwise init and the tolerant decode.
type swiftField struct {
	prop     string
	typ      string
	optional bool
	defExpr  string
}

func genMessage(g *protogen.GeneratedFile, m *protogen.Message) error {
	name := m.GoIdent.GoName
	var fields []swiftField
	for _, field := range m.Fields {
		sf, err := mapField(field)
		if err != nil {
			return fmt.Errorf("%s.%s: %w", name, field.Desc.Name(), err)
		}
		fields = append(fields, sf)
	}

	g.P("public struct ", name, ": Codable, Sendable {")
	for _, sf := range fields {
		g.P("    public var ", sf.prop, ": ", declType(sf))
	}
	g.P()

	// memberwise init with proto3 defaults, so callers construct one ergonomically.
	g.P("    public init(")
	for i, sf := range fields {
		comma := ","
		if i == len(fields)-1 {
			comma = ""
		}
		def := sf.defExpr
		if sf.optional {
			def = "nil"
		}
		g.P("        ", sf.prop, ": ", declType(sf), " = ", def, comma)
	}
	g.P("    ) {")
	for _, sf := range fields {
		g.P("        self.", sf.prop, " = ", sf.prop)
	}
	g.P("    }")
	g.P()

	// tolerant decode: a field omitted at its proto3 default is absent on the wire.
	g.P("    public init(from decoder: any Decoder) throws {")
	g.P("        let c = try decoder.container(keyedBy: CodingKeys.self)")
	for _, sf := range fields {
		if sf.optional {
			g.P("        self.", sf.prop, " = try c.decodeIfPresent(", sf.typ, ".self, forKey: .", sf.prop, ")")
		} else {
			g.P("        self.", sf.prop, " = try c.decodeIfPresent(", sf.typ, ".self, forKey: .", sf.prop, ") ?? ", sf.defExpr)
		}
	}
	g.P("    }")
	g.P()

	// CodingKeys: the property name already equals the protojson key (lowerCamel), so
	// synthesized encoding emits protojson without an override.
	g.P("    enum CodingKeys: String, CodingKey {")
	for _, sf := range fields {
		g.P("        case ", sf.prop)
	}
	g.P("    }")
	g.P("}")
	g.P()
	return nil
}

// declType is the property/parameter type as written (adds the `?` for optionals).
func declType(sf swiftField) string {
	if sf.optional {
		return sf.typ + "?"
	}
	return sf.typ
}

func mapField(field *protogen.Field) (swiftField, error) {
	prop := lowerCamel(string(field.Desc.Name()))

	if field.Desc.IsMap() {
		k := field.Desc.MapKey().Kind()
		v := field.Desc.MapValue().Kind()
		if k != protoreflect.StringKind || v != protoreflect.StringKind {
			return swiftField{}, fmt.Errorf("only map<string, string> is supported (teach the emitter)")
		}
		return swiftField{prop: prop, typ: "[String: String]", defExpr: "[:]"}, nil
	}

	base, def, err := baseType(field)
	if err != nil {
		return swiftField{}, err
	}
	if field.Desc.IsList() {
		return swiftField{prop: prop, typ: "[" + base + "]", defExpr: "[]"}, nil
	}
	if field.Desc.Kind() == protoreflect.MessageKind {
		// a singular message has no proto3 default value -> optional.
		return swiftField{prop: prop, typ: base, optional: true}, nil
	}
	return swiftField{prop: prop, typ: base, defExpr: def}, nil
}

// baseType maps one scalar/enum/message field kind to its Swift type and proto3 default
// expression. Anything outside the supported set is a hard error.
func baseType(field *protogen.Field) (typ, def string, err error) {
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		return "String", "\"\"", nil
	case protoreflect.EnumKind:
		return field.Enum.GoIdent.GoName, ".default", nil
	case protoreflect.MessageKind:
		return field.Message.GoIdent.GoName, "", nil
	default:
		return "", "", fmt.Errorf("unsupported field kind %q (teach the emitter)", field.Desc.Kind())
	}
}

// lowerCamel converts a proto snake_case or SCREAMING_SNAKE name to lowerCamelCase
// (model_id -> modelId, ROLE_TRANSCRIPTION -> roleTranscription).
func lowerCamel(s string) string {
	var b strings.Builder
	for i, part := range strings.Split(s, "_") {
		if part == "" {
			continue
		}
		part = strings.ToLower(part)
		if i == 0 {
			b.WriteString(part)
		} else {
			b.WriteString(strings.ToUpper(part[:1]))
			b.WriteString(part[1:])
		}
	}
	return b.String()
}
